Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [9]:
import numpy as np

num = int(input('Введите число: '))
np.arange(num - 1, -1, -1)


Введите число: 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [22]:
import numpy as np

num = int(input('Введите число N: '))
# print(np.diag(np.arange(num - 1, -1, -1)))
# print(sum(np.diag(np.arange(num - 1, -1, -1), k=0)))
sum(sum(np.diag(np.arange(num - 1, -1, -1), k=0)))



Введите число N: 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
[9 8 7 6 5 4 3 2 1 0]


45

In [ ]:
Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [30]:
import numpy as np
from numpy import linalg

eqv_a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
eqv_b = np.array([4, 12, -3])

linalg.solve(eqv_a, eqv_b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [31]:
np.allclose( np.dot(eqv_a, linalg.solve(eqv_a, eqv_b)), eqv_b ) # проверка

True

Задание 4

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

"""На сайт заходит очередной посетитель, о покупках которого известно следующее:"""

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

"""
Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное расстояние между этим пользователем и 
всеми пользователями из массива user_stats

"""


In [49]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )


max = 0
for i, user in enumerate(users_stats):
    print(i + 1, cosine(user, next_user_stats))
    if max < cosine(user, next_user_stats):
        max = cosine(user, next_user_stats)
        max_id = i +1
print('Наиболее близкий покупатель: ID', max_id)



1 0.19999999999999996
2 0.8451542547285165
3 0.3999999999999999
4 0.7905694150420948
5 0.3999999999999999
6 0.0
7 0.0
8 0.9486832980505138
9 0.0
10 0.0
Наиболее близкий покупатель: ID 8
